import type { Metadata } from "next";

import "@/app/globals.css";

export const metadata: Metadata = {
  title: "FCAI Theatre",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // console.log(params.locale);
  return (
    <>
     
        {children}
     
    </>
  );
}
