import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "@/app/globals.css";
import Navbar from "@/components/navigation/navbar";
import { dir } from "i18next";
import i18nConfig, { Locale } from "@/next-i18next.config";
import { SessionProvider } from "next-auth/react";
import ScrollToTopButton from "@/components/helpers/scroll-to-top-button";
import TranslationsProvider from "@/components/providers/translation-provider";
import { constantsNamespaces } from "@/lib/namespaces";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/providers/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FCAI Theatre cast",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale: locale }));
}

export default function MainLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: {
    locale: Locale;
  };
}) {
  // console.log(params.locale);
  return (
    <html
      lang={params.locale ? params.locale : i18nConfig.defaultLocale}
      dir={params.locale ? dir(params.locale) : dir(i18nConfig.defaultLocale)}
      suppressHydrationWarning
    >
      <body className={cn("min-h-screen w-full", inter.className)}>
        <SessionProvider>
          <TranslationsProvider locale={params.locale} namespaces={constantsNamespaces}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            storageKey="theatre-theme"
            enableSystem
            disableTransitionOnChange
          >
            <Navbar
              locale={params.locale}
              className="general-padding min-h-[var(--header-height)]"
            />
            {children}
          </ThemeProvider>
          </TranslationsProvider>
          <ScrollToTopButton />
        </SessionProvider>
      </body>
    </html>
  );
}
